apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: taint-test
  name: taint-test
  namespace: default
spec:
  replicas: 10
  selector:
    matchLabels:
      app: taint-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: taint-test
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: kurum
                operator: In
                values:
                - cevresehir
      tolerations:
      - key: "kurum"
        operator: "Equal"
        value: "cevresehir"
        effect: "NoSchedule"
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 10
  conditions:
  - lastTransitionTime: "2026-06-12T12:46:47Z"
    lastUpdateTime: "2026-06-12T12:46:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-06-12T12:46:46Z"
    lastUpdateTime: "2026-06-12T12:46:47Z"
    message: ReplicaSet "taint-test-56ccd57d9f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 10
  replicas: 10
  terminatingReplicas: 0
  updatedReplicas: 10
