  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: k8s-playground-ingressss
    namespace: cahit
  spec:
    ingressClassName: nginx
    rules:
      - host: k8s.aselsan.com
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: dotnet-test
                  port:
                    number: 8091
              path: /