apiVersion: v1
kind: Secret
metadata:
  name: playground-secret
  namespace: playground
type: Opaque
stringData:
  # Bunlar Pod'a env değişkeni olarak aktarılacak
  DB_PASSWORD: "S3cret!Training"
  API_TOKEN: "tok_demo_1234567890"
  # Volume olarak mount edildiğinde her anahtar bir dosya olur
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    DEMO_ANAHTAR_GERCEK_DEGIL
    -----END PRIVATE KEY-----
