apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playground-data
  namespace: playground
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  # Minikube'de varsayılan StorageClass 'standard'dır.
  # storageClassName: standard
