apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-sa
  namespace: default
  labels:
    app: sa-demo
# automountServiceAccountToken'ı burada SA seviyesinde de set edebilirsiniz.
# false yapılırsa bu SA'yı kullanan tüm Pod'lar token'sız çalışır.
# automountServiceAccountToken: false
